<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Comments
 */
?>
<?php
    $comments = $block->getCommentsCollection();
    $numberOfCommentsToDisplay = $block->getNumberOfComments();
    $session = $block->getCustomerSession();

    $canPost = $block->canPost();
?>
<div id="post-comments">
    <div class="c-count container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-gray-300 border-b-2  md:flex-row">
        <strong class="text-2xl font-medium text-gray-900 title-font"><?= $block->escapeHtml(__('%1 Comment(s)', $block->getPost()->getCommentsCount())) ?></strong>
    </div>
    <!-- reply form -->
    <div class="c-reply cf mb-4">
        <?php if ($image = $block->getCustomerImage()) { ?>
        <div class="c-img">
            <img src="<?= $block->escapeUrl($image) ?>" alt="<?= $block->escapeHtml($block->getCustomerName()) ?>">
        </div>
        <?php } ?>
        <div class="c-replyform <?php if ($canPost) {  echo 'no-active'; } ?>">
            <form class="comment-form-blog-recaptcha"
                  action="<?= $block->escapeUrl($block->getFormUrl()) ?>"
                  method="post">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="post_id" value="<?= (int)($block->getPost()->getId()) ?>" />
                <textarea name="text" class="w-full"
                          placeholder="<?= $canPost ? $block->escapeHtml(__('Add a comment...')) : $block->escapeHtml(__('Sign in to add a comment...')) ?>" <?php if (!$canPost) {?>
                          disabled="disabled"<?php } ?>
                          required
                          data-validate="{required:true}"></textarea>
                <div class="c-btn-hld hidden">

                    <?php if ($canPost && !$session->getCustomerGroupId()) { ?>
                    <div class="lr-hld">
                        <div class="left-hld">
                            <input type="text"
                                   name="author_nickname"
                                   value=""
                                   placeholder="<?= $block->escapeHtml(__('Full Name')) ?>"
                                   class="input-text required-entry w-full"
                                   data-validate="{required:true}"
                                   autocomplete="off"
                                   required
                                   aria-required="true">
                        </div>
                        <div class="right-hld">
                            <input type="email"
                                   name="author_email"
                                   autocomplete="email"
                                   value=""
                                   placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                                   class="input-text w-full"
                                   required
                                   data-validate="{required:true, 'validate-email':true}"
                                   aria-required="true">
                        </div>
                    </div>
                    <?php } ?>

                    <?php if ($block->displayPrivacyPolicyCheckbox()) { ?>
                        <?= $block->getChildBlock('display_privacy_policy_checkbox')->setCommentType('post')->toHtml(); ?>
                    <?php } ?>
                    <div class="clearfix"></div>

                    <div id="recaptcha-append-to"><?= $block->getChildHtml('blog.post.comments.magefan.additional'); ?></div>

                    <?php if ($canPost) { ?>
                        <button type="submit"><?= $block->escapeHtml(__('Submit')) ?></button>
                    <?php } else { ?>
                        <button type="button"
                                onclick="window.location='<?= $block->escapeUrl($block->getCustomerUrl()->getLoginUrl()) ?>';">
                            <?= $block->escapeHtml(__('Sign In')) ?>
                        </button>
                    <?php } ?>

                </div>
            </form>
        </div>
    </div>
<?php
    $commentsCount = count($comments);
if ($commentsCount) {
    ?>
    <!-- comments list -->
    <div class="c-comments pt-7 pl-6 border-gray-300 border-t-2" >
    <?php $i = 0 ?>
    <?php foreach ($comments as $comment) { ?>
            <?php
                $i++;
                $comment->setIsHidden($i > $numberOfCommentsToDisplay);
            ?>
            <?= $block->getCommentHtml($comment) ?>
        <?php } ?>
        <?php if ($commentsCount > $numberOfCommentsToDisplay) { ?>
            <a href="#" class="c-allcomments more-comments-action block w-full text-center text-white py-2.5 px-3 bg-[#1d4ed8] hover:bg-[#2563eb]" data-comment="0"><?= $block->escapeHtml(__('Load more comments')) ?></a>
        <?php } ?>
    </div>

    <!-- reply comment form -->
    <div id="c-replyform-comment" class="c-replyform c-replyform-comment mb-4" style="display:none">
        <form class="reply-form-blog-recaptcha"
              action="<?= $block->escapeUrl($block->getFormUrl()) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="post_id" value="<?= $block->escapeHtml($block->getPost()->getId()) ?>" />
            <input type="hidden" name="parent_id" value="" />
            <textarea class="refresh-value w-full"
                      name="text"
                      placeholder="<?= $canPost ? $block->escapeHtml(__('Add a reply...')) : $block->escapeHtml(__('Sign in to add a comment...')) ?>" <?php if (!$canPost) {?>
                      disabled="disabled"<?php } ?>
                      required
                      data-validate="{required:true}"></textarea>
            <div class="c-btn-hld">

            <?php if ($canPost && !$session->getCustomerGroupId()) { ?>
                <div class="lr-hld">
                    <div class="left-hld">
                        <input type="text"
                               name="author_nickname"
                               value=""
                               placeholder="<?= $block->escapeHtml(__('Full Name')) ?>"
                               class="input-text required-entry refresh-value w-full"
                               data-validate="{required:true}"
                               required
                               autocomplete="off"
                               aria-required="true">
                    </div>
                    <div class="right-hld">
                        <input type="email"
                               name="author_email"
                               autocomplete="email"
                               value=""
                               placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                               class="input-text required-entry refresh-value w-full"
                               data-validate="{required:true, 'validate-email':true}"
                               required
                               aria-required="true">
                    </div>
                </div>
                <?php } ?>
                <button type="button" class="cancel reply-cancel-action" ><?= $block->escapeHtml(__('Cancel')) ?></button>
            <?php if ($canPost) { ?>
                    <button type="submit"><?= $block->escapeHtml(__('Submit')) ?></button>
                    <?php if ($block->displayPrivacyPolicyCheckbox()) { ?>
                        <?= $block->getChildBlock('display_privacy_policy_checkbox')->setCommentType('comment')->toHtml(); ?>
                    <?php } ?>
                <?php } else { ?>
                    <?php if ($block->displayPrivacyPolicyCheckbox()) { ?>
                        <?= $block->getChildBlock('display_privacy_policy_checkbox')->setCommentType('comment')->toHtml(); ?>
                    <?php } ?>
                    <button type="button"
                            onclick="window.location='<?= $block->escapeUrl($block->getCustomerUrl()->getLoginUrl()) ?>';">
                        <?= $block->escapeHtml(__('Sign In')) ?>
                    </button>
                <?php } ?>
                <div class="clearfix"></div>
                <div id="recaptcha-reply-append-to"><?= $block->getChildHtml('blog.post.comments.magefan.reply.additional'); ?></div>
            </div>
        </form>
    </div>
<?php } ?>
</div>

<script>
    var _deepestScroll = 0;

    function initCommentsJs(firstCheck) {
        if (!firstCheck && _deepestScroll + 50 > document.documentElement.scrollTop) {
            return;
        }

        _deepestScroll = document.documentElement.scrollTop;

        let commentElement = document.querySelector('._post-view .comments');
        let offset = 50;

        let isCommentElementVisible = ((commentElement.getBoundingClientRect().top - offset) < window.innerHeight);

        if (isCommentElementVisible) {
            document.removeEventListener('scroll', initCommentsJs);

            const script = document.createElement('script');
            script.type = 'text/javascript';
            script.src = '<?= $escaper->escapeUrl($block->getViewFileUrl('Hyva_MagefanBlog/js/magefan-comments.js')) ?>';
            document.head.append(script);
        }
    }

    initCommentsJs(true);
    document.addEventListener('scroll', initCommentsJs);
</script>
