<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
<div class="widget block block-tagclaud mt-5" data-bind="scope: 'tagclaud'">
    <div class="title text-md md:text-lg font-semibold py-2">
        <strong><?= $block->escapeHtml(__('Tags')) ?></strong>
    </div>

    <div id="blogSidebarCloudCanvasContainer">
        <canvas style="width:100%" height="<?= $block->escapeHtml($block->getConfigValue($block::CLOUD_HEIGHT)) ?>" id="blogSidebarCloudCanvas">
            <div id="tags" class="tagclaud-hld">
                <?php foreach ($tags as $tag) { ?>
                    <?php $title = $tag->getTitle() ?>
                    <span class="<?= $block->escapeHtml($block->getTagClass($tag)) ?>">
                        <a href="<?= $block->escapeUrl($tag->getTagUrl()) ?>" title="<?= $block->escapeHtml($title) ?>">
                            <?= $block->escapeHtml($title) ?>
                         </a>
                    </span>
                <?php } ?>
            </div>
        </canvas>
    </div>
</div>

    <script>
        var _deepestScroll = 0;

        function initTagCanvas(firstCheck) {
            if (!firstCheck && _deepestScroll + 50 > document.documentElement.scrollTop) {
                return;
            }

            _deepestScroll = document.documentElement.scrollTop;

            let commentElement = document.querySelector('#blogSidebarCloudCanvas');
            let offset = 50;

            let isCommentElementVisible = ((commentElement.getBoundingClientRect().top - offset) < window.innerHeight);

            if (isCommentElementVisible) {
                document.removeEventListener('scroll', initTagCanvas);

                const script = document.createElement('script')
                script.src = '<?= $escaper->escapeUrl($block->getViewFileUrl('Hyva_MagefanBlog/js/tagcanvas.min.js')) ?>';
                script.addEventListener('load', function () {
                    try {
                        TagCanvas.Start('blogSidebarCloudCanvas','tags', <?= /*@noEscape*/ $block->getAnimationConfig() ?>);
                    } catch(e) {
                        // something went wrong, hide the canvas container
                        document.getElementById('blogSidebarCloudCanvasContainer').style.display = 'none';
                    }
                });
                document.head.append(script);
            }
        }

        initTagCanvas(true);
        document.addEventListener('scroll', initTagCanvas);
    </script>
<?php } ?>


