<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null);
?>

<style>
    .post-content h2 {font-size: 1.6rem;line-height: 1.8rem;margin-top: 1em;margin-bottom: 0.8em;}
    .post-content p {margin-bottom: 0.8em;}
    .post-content ul {margin-bottom: 0.8em;}
    .post-content ol {margin-bottom: 0.8em;}
</style>

<div class="post-view card">
    <div class="post-holder post-holder-<?= (int)$_post->getId() ?>">

        <?php if ($block->displayAddThisToolbox()) : ?>
          <div class="post-header">
              <div class="addthis_toolbox addthis_default_style float-right" addthis:url="<?= $block->escapeUrl($_postUrl) ?>">
                  <a class="addthis_button_facebook"></a>
                  <a class="addthis_button_twitter"></a>
                  <a class="addthis_button_email"></a>
                  <a class="addthis_button_compact"></a>
              </div>
              <?= $block->getInfoHtml() ?>
          </div>
        <?php endif; ?>

        <div class="post-content">
            <div class="post-description clearfix">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <?php
                    $featuredImgAlt = $_post->getData('featured_img_alt');
                    if (!$featuredImgAlt) {
                        $featuredImgAlt = $_postName;
                    }
                    ?>
                    <div class="post-ftimg-hld mb-5">
                        <img src="<?= $block->escapeUrl($featuredImage) ?>" alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                    </div>
                <?php } ?>
                <div class="post-text-hld">
                    <?= /*@noEscape*/ $block->getContent() ?>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>

        <div class="post-bottom mt-8">
            <?= $block->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>