<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Comments\Magefan\Comment
 */
?>
<?php
    $comment = $block->getComment();
    $numberOfCommentsToDisplay = $block->getNumberOfReplies();
?>
<div class="c-comment c-comment-parent-<?= (int)$comment->getParentId() ?> border-b-2 border-dashed mb-5" <?= $comment->getIsHidden() ? 'style="display:none"' : '' ?>>
    <?php if ($authorImage = $comment->getAuthorImage()) { ?>
    <div class="c-img">
        <img src="<?= $block->escapeUrl($authorImage) ?>" alt="<?= $block->escapeHtml($comment->getAuthorName()) ?>">
    </div>
    <?php } ?>
    <div class="c-post c-post-<?= (int)$comment->getId() ?>" id="c-post-<?= (int)$comment->getId() ?>">
        <div class="p-info mb-2.5">
            <div class="p-name inline-block font-bold mr-2.5"><?= $block->escapeHtml($comment->getAuthor()->getNickname()) ?></div>
            <div class="publish-date inline-block text-gray-300 text-xs"><?php echo $block->escapeHtml($block->getPublishDate()) ?></div>
        </div>

        <div class="p-text mb-2.5"><?= /*@noEscape*/ nl2br($block->escapeHtml($comment->getText())) ?></div>
        <div class="p-actions mb-2.5">
            <a href="#" class="reply-action text-gray-300 text-xs"
               data-comment="<?= $comment->isReply() ?
                   (int)$comment->getParentId() :
                   (int)$comment->getId() ?>"
               title="<?= $block->escapeHtml(__('Reply')) ?>"><?= $block->escapeHtml(__('Reply')) ?></a>
        </div>
        <?php
            $replies = $block->getRepliesCollection();
            $commentsCount = count($replies);
        if ($commentsCount) {
            ?>
            <div class="p-replies pl-3 border-l-2 border-dashed">
            <?php $i = 0 ?>
            <?php foreach ($replies as $reply) { ?>
                    <?php
                        $i++;
                        $reply->setIsHidden($i > $numberOfCommentsToDisplay);
                    ?>
                    <?= /*@noEscape*/ $block->setComment($reply)->toHtml() ?>
                <?php } ?>

                <?php if ($commentsCount > $numberOfCommentsToDisplay) { ?>
                <div class="c-more more-comments-action" data-comment="<?= (int)$comment->getId() ?>">
                    <a href="#" ><?= $block->escapeHtml(__('Show more replies in this thread')) ?><i></i></a>
                </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>
